name: flutter_chart
description: Flutter Canvas draws Bezier curves and histograms, embeds animations, and the entire drawing process is clearly visible. A very interesting Widget
version: 0.1.3
author: xt.sun<xingtao.sun@gmail.com>
homepage: https://blog.csdn.net/sxt_zls

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

