name: d5_cylinder
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  flutter_section_table_view: ^1.0.5
  english_words: ^3.1.0
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.1.1
  # https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^5.0.2
#  permission: ^0.1.2 #获取设备读写权限
  # 本地文件读写
  path_provider: ^1.1.2
  # 常用工具类
  flustars: ^0.2.6+1
  provide: ^1.0.2 #数据管理层
  package_info: ^0.4.0+6 #获取app信息
  #rxdart
  rxdart: ^0.22.0
  # webview_flutter
  webview_flutter: ^0.3.4
  # Flutter 国际化/多语言库 https://github.com/Sky24n/fluintl
  fluintl: ^0.1.2
  # Flutter WebSokcet web_socket_channel
  web_socket_channel: 1.0.13
  # Flutter log4d 日志文件输出
  log4d: ^1.0.4
  fluttertoast: ^3.1.0 #提示框
  #存储键值对信息
  shared_preferences: ^0.5.3+4
  # Flutter charts_common 绘制图表
  scoped_model: ^1.0.1
  charts_common: ^0.6.0
  charts_flutter: ^0.6.0
  flutter_chart:
    path: thirdLib/flutter_chart/
  # Flutter flutter_circular_chart 绘制圆环图表
  flutter_circular_chart: ^0.1.0
  # Flutter flutter_circular_chart 绘制柱状图
  fl_chart: ^0.1.3
#  dev_dependencies:
#  flutter_test:
#    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/data/smoothline.json
    - assets/images/amazon_logo_beacon.png
    - assets/images/user_bg.png
    - assets/images/user_service.png
    - assets/images/user_collect.png
    - assets/images/user_help.png
    - assets/images/user_setting.png
    - assets/images/user_about.png
    - assets/images/list_in.png
    - assets/images/virtual_titleBack.png
    - assets/images/machine_bg.png
    - assets/images/jiqiren.png
    - assets/images/cutter.png
    - assets/images/arror_right.png
    - assets/images/zuobiaofansuanlicheng.png
    - assets/images/jixieshebei.png
    - assets/images/fsux_tubiao_duijizhuzhuangtu.png
    - assets/images/jiqishebei.png
    - assets/images/FOXNUM.gif
    - assets/images/00.png
    - assets/images/01.png
    - assets/images/02.png
    - assets/images/03.png
    - assets/images/04.png
    - assets/images/05.png
    - assets/images/06.png
    - assets/images/07.png
    - assets/images/08.png
    - assets/images/09.png




  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
